### ISSUE TITLE
create main storyline for chapter 1

### ISSUE THREAD

**Issue by thewro11** [the-crazy-Swamps/game#1]
creating the main storyline.

[finalcap1.docx](https://github.com/the-crazy-Swamps/game/files/14731868/finalcap1.docx)

Acceptance Criteria:
- Storyline is written completely.

**Comment by zanuez** [comment]
update story 6/1/2024

**Comment by zanuez** [comment]
update story 20/1/2024

**Comment by thewro11** [comment]
@zanuez Please update the latest storyline in the comment of this issue.
