### ISSUE TITLE
research for sample character models and tilemaps

### ISSUE THREAD

**Issue by thewro11** [the-crazy-Swamps/game#16]
Acceptance Criteria:
- Research for sample character models that could be used in Unity project in either 2D (file extension should be .psd) or 3D (file extension should be .obj).
- Research for sample tilemaps that could be used in Unity projet in either 2D or 3D.
- This issue only focus on researching the specified files above, though assignees are not required to test them in Unity projects oneself.

**Comment by thewro11** [comment]
Please search for these materials:
- Model of humanoid character(s)
- Model of fluid character(s)/monster(s) - a model which does not have the exact object designed for movement such as arms and legs.
- 2D or 3D Tilemap(s)

**Comment by PrArisa** [comment]
เนื่องจากบางไฟล์ไม่รองราับดังนั้นจะแบบ Google Drive แทน
https://drive.google.com/drive/folders/1KOLN3kEor_Xhmb6ACfn51z_JyvXf-hB9?usp=drive_link

หมายเหตุ : โมเดลที่ใช้เป็นโมเดลฟรี บางโมเดลติดข้อตกลงในการใช้ส่วนบุคคลเท่านั้น มีจุดประสงค์ในการศึกษาโมเดล ดังนั้นห้ามเอาไปใช้ในเชิงพานิชย์ทุกกรณี

หากต้องการคโมเดลเพิ่มเติมสามารถแจ้งไปยังผู้รับผิดชอบได้ จะมาอัปเดตหากมีการเพิ่มโมเดลในภายหลัง
