### ISSUE TITLE
create monster art "Goblin"

### ISSUE THREAD

**Issue by thewro11** [the-crazy-Swamps/game#18]
Acceptance Criteria:
- Create the monster art "goblin".

**Comment by PrArisa** [comment]
![Image](https://github.com/the-crazy-Swamps/game/assets/134216200/871379c8-7008-4f20-8704-22445abb3fec)

**Comment by PrArisa** [comment]
1. concept art with line art
2. Goblin No.1 .png
3. Goblin No.2 .png

![Goblin01](https://github.com/the-crazy-Swamps/game/assets/134216200/b463b0ce-c9ff-47cc-a23a-2824f272acef)
![Goblin02](https://github.com/the-crazy-Swamps/game/assets/134216200/acffadf7-8e8b-45c5-a369-9f6d21c56a86)
![01](https://github.com/the-crazy-Swamps/game/assets/134216200/4f870cef-f6e0-4d6c-90d0-34d99d74f685)

**Comment by zanuez** [comment]
Request
-model
-final model

**Comment by thewro11** [comment]
@zanuez Please create into a new issue. This issue is now completed
