### ISSUE TITLE
create the concept art for Daneef City

### ISSUE THREAD

**Issue by thewro11** [the-crazy-Swamps/game#4]
Daneef City is the first city where player would encounter in the beginning of the story.

Acceptance Criteria:
- Design how Daneef City would look like.

**Comment by PESTREL** [comment]
- พื้นที่ตีก็อบลิน
- ค่ายทหาร

(ยังไม่มา)
- พื้นที่อาศัย(ชายขอบ)
- พื้นที่ตีมอนอื่น ๆ

![Image](https://github.com/the-crazy-Swamps/game/assets/134216178/35935324-3e2b-4cfb-9a99-6abb5dbd5b10)
![Image](https://github.com/the-crazy-Swamps/game/assets/134216178/df542e1d-82e9-4d68-8c23-0a9d7558cd1a)

**Comment by thewro11** [comment]
This can be marked as completed, as you already have some concepts about the city.

**Comment by PESTREL** [comment]
อัปเดตภาพสุดท้ายที่ทำค้างไว้ -- เริ่มทำ issue ใหม่

![game](https://github.com/the-crazy-Swamps/game/assets/134216178/8437741d-b452-4232-8fec-68605a73b3cc)
![game2](https://github.com/the-crazy-Swamps/game/assets/134216178/d0b3b1cf-51f0-46e2-853d-0ac80ccfbce1)
![game3](https://github.com/the-crazy-Swamps/game/assets/134216178/f013feed-5d4b-4951-90fd-400f5eaafe22)
