### ISSUE TITLE
create the concept art for characters in Daneef City

### ISSUE THREAD

**Issue by thewro11** [the-crazy-Swamps/game#5]
As we have had the brief background of Daneef City, we can think about the citizen in the city.

Acceptance Criteria:
- Design how the characters in Daneef City would look like.

**Comment by PrArisa** [comment]
Dwaft#1
![Illustration1](https://github.com/the-crazy-Swamps/game/assets/134216200/bd93d1ea-5f75-4977-80da-fa27ae45bc3b)
![Illustration2](https://github.com/the-crazy-Swamps/game/assets/134216200/dc22302a-377e-4e6d-97fa-1efb80f516b5)

**Comment by PrArisa** [comment]
Vampire#1
![Illustration3](https://github.com/the-crazy-Swamps/game/assets/134216200/d81c030b-30fc-4c51-8eb4-d0c14304a230)
![Illustration4](https://github.com/the-crazy-Swamps/game/assets/134216200/8416730f-16c3-4abd-9e17-9e2a09c4d446)

**Comment by thewro11** [comment]
This can be marked as completed, as you already have some concepts about the characters in Daneef.
