### ISSUE TITLE
research game sound effects

### ISSUE THREAD

**Issue by thewro11** [the-crazy-Swamps/game#7]
Acceptance Criteria:
- Find sources of musics or sounds that we can use in our project (in term of marketing).
- Research on copyright related to usage of sounds from those external sources.
- Share with team.

**Comment by dragonknighx** [comment]
Sound clound (ฟรี) : https://soundcloud.com/
Youtube (ฟรี) : https://www.youtube.com/
Envato (จ่ายค่าซัพ) : https://www.envato.com/

**Comment by thewro11** [comment]
In a free and accessible websites, such as SoundCloud, YouTube, etc., how can you classify each medias as **commercial-usable** or **commercial-unusable**?

**Comment by dragonknighx** [comment]
Always make sure to read and understand the terms and conditions associated with each piece of sound you are about to use. Many creatures will put it in the Description, but if they don't make sure to ask the creator

If you're unsure about the usage rights of it, consider reaching out to the creator for clarification or seek legal advice to comply with copyright laws.
